name: unsplash_client
description: An unofficial, platform independent client for accessing the Unsplash.com REST api.
version: 0.2.1
repository: https://github.com/blaugold/unsplash_client
issue_tracker: https://github.com/blaugold/unsplash_client/issues
homepage: https://github.com/blaugold/unsplash_client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  http: ^0.12.2
  collection: ^1.14.12

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  matcher: ^0.12.9
  path: ^1.7.0
